# Generated by Django 5.1.3 on 2025-01-29 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField(help_text='În cm')),
                ('weight', models.FloatField(help_text='În kg')),
                ('gender', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=10)),
                ('objective', models.IntegerField(choices=[(1, 'Slăbit'), (2, 'Punere în greutate'), (3, 'Creștere masă musculară'), (4, 'Recompoziție corporală')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
