# Generated by Django 5.1.3 on 2025-04-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_quizresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'Sedentar (activitate minimă, job de birou)'), (2, 'Ușor activ (exerciții ușoare 1-3 zile/săptămână)'), (3, 'Moderat activ (exerciții moderate 3-5 zile/săptămână)'), (4, 'Foarte activ (exerciții intense 6-7 zile/săptămână)'), (5, 'Extrem de activ (exerciții intense zilnic, job fizic sau antrenament de 2x/zi)')], default=1),
        ),
    ]
