# Generated by Django 5.1.3 on 2025-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_quizresponse_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='bmr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='tdee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
