# Generated by Django 5.1.3 on 2025-04-06 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_quizresponse_bmr_quizresponse_tdee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('food_category', models.CharField(blank=True, max_length=100, null=True)),
                ('serving_size', models.FloatField(default=100.0)),
                ('serving_unit', models.CharField(default='g', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Mic dejun'), ('lunch', 'Prânz'), ('dinner', 'Cină'), ('snack', 'Gustare')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Gramaj')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='myapp.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_calories', models.FloatField()),
                ('target_protein', models.FloatField()),
                ('target_carbs', models.FloatField()),
                ('target_fat', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Luni'), (2, 'Marți'), (3, 'Miercuri'), (4, 'Joi'), (5, 'Vineri'), (6, 'Sâmbătă'), (7, 'Duminică')])),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='myapp.mealplan')),
            ],
            options={
                'unique_together': {('meal_plan', 'day')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_plan_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='myapp.mealplanday'),
        ),
    ]
